version: '3.7'
services:
  advent-of-code:
    image: docker.okidoo.co/node-dev:latest
    container_name: advent-of-code
    dns: 1.1.1.1
    env_file:
      - ./.git.env
    volumes:
      - ./.npmrc:/home/node/.npmrc
      - ../:/home/node/app
      - ~/.ssh/:/home/node/.ssh/
    command: tail -F anything